Pasta:

- name: Spaghetti
  ingredients: With marinara sauce and mozzarella cheese. 
  price: $8.95
- name: Spaghetti with meatballs or sausage or mushrooms
  ingredients: With marinara sauce and mozzarella cheese. 
  price: $10.90
- name: Homemade Meat Lasagna
  ingredients: Marinara sauce, mozzarella and ricotta cheese. 
  price: $9.95
- name: Homemade Meat Lasagna with choice of fresh mushrooms, italian sausage or meatballs
  ingredients: Marinara sauce, mozzarella and ricotta cheese. 
  price: $11.90
- name: Beef Ravioli
  ingredients: Marinara sauce and mozzarella cheese. 
  price: $9.50
- name: Cheese Ravioli
  ingredients: Marinara sauce and mozzarella cheese. 
  price: $9.50
- name: Spinach Ravioli
  ingredients: Marinara sauce and mozzarella cheese.
  price: $9.50
- name: Penne Napolitan
  ingredients: Italian sausage sauteed with garlic, peas, tomato sauce, cream sauce, Parmesan tossed with penne. 
  price: $9.50
- name: Baked Ziti
  ingredients: Penne mixed with ricotta, fresh basil and marinara sauce, baked under a blanket of mozzarella cheese. 
  price: $8.95
- name: Baked Ziti with choice of Italian sausage or homemade meatballs
  ingredients: Penne mixed with ricotta, fresh basil and marinara sauce, baked under a blanket of mozzarella cheese. 
  price: $10.90
- name: Chicken Spinach Penne
  ingredients: Chicken breast, fresh spinach, mushrooms, artichoke, garlic, Parmesan and tomato sauce. 
  price: $9.95
- name: Chicken Pesto
  ingredients: Sauteed chicken breast, fresh pesto, mushrooms, garlic, Parmesan and a touch of cream tossed with penne. 
  price: $9.95
- name: Garlic Shrimp
  ingredients: Large shrimp with tomato, olive oil, garlic, Parmesan, white wine and cream sauce tossed with linguini. 
  price: $10.95
- name: Tortellini Primavera
  ingredients: Cheese tortellini with choice of cream sauce or tomato sauce, mozzarella cheese and fresh vegetables. 
  price: $9.95
- name: Chicken Parmesan
  ingredients: With marinara sauce and mozzarella on a bed of fettuccini. 
  price: $9.95
- name: Eggplant Parmesan
  ingredients: With marinara sauce and mozzarella on a bed of fettuccini. 
  price: $9.25
- name: Chicken Alfedo
  ingredients: Cream sauce and Parmesan cheese on a bed of fettuccini. 
  price: $9.95
- name: Fettucini Verdura
  ingredients: Cream sauce, fresh vegetables and Parmesan cheese. 
  price: $9.25
- name: Angel Hair Pomodoro
  ingredients: Fresh Roma tomatoes, fresh basil, garlic, mushroom, Parmesan cheese, white wine and olive oil. 
  price: $9.95
- name: Angel Hair Pomodoro with breast of chicken
  ingredients: Fresh Roma tomatoes, fresh basil, garlic, mushroom, Parmesan cheese, white wine and olive oil. 
  price: $11.90
- name: Cajun Chicken Chipotle
  ingredients: Chicken breast marinated in cajun vinaigrette, sauteed with sweet red peppers, red onions and garlic and tossed with chipotle chili cream sauce and linguini. Topped with fresh tomato and cilantro. 
  price: $9.95
- name: Chicken Spinach Lasagna
  ingredients: Tender pieces of chicken breast and fresh spinach layered with ricotta and mozzarella cheese, pasta,  Parmesan and cream sauce. 
  price: $9.95