Salads:
- name: Caesar Salad
  ingredients:  Romaine, garlic croutons and Parmesan cheese with Caesar dressing. Served with garlic bread.
  price: $6.50
- name: Caesar Salad with extra grilled chicken
  ingredients:  Romaine, garlic croutons and Parmesan cheese with Caesar dressing. Served with garlic bread.
  price: $9.00
- name: Antipasto Salad
  ingredients:  Salami, ham, pepperoni, red onion, black olives, tomatoes, mozzarella cheese and pepperoncini. Served with garlic bread and your choice of dressing.
  price: $8.99
- name: Tossed Chicken Salad
  ingredients:  Chicken breast with lettuce, tomatoes, red onion, pepperoncini, black olive and mozzarella cheese. Served with garlic bread and your choice of dressing.
  price: $9.85
- name: Spinach Chicken Salad
  ingredients:  Spinach topped with avocados, grilled chicken breast, artichoke hearts, tomatoes, mushrooms, croutons and Parmesan cheese. Served with garlic bread and your choice of dressing.
  price: $9.85
- name: Greek Salad
  ingredients:  Blend of mixed greens and baby lettuce with Roma tomatoes, Greek olives, cucumber, red onions, pepperoncini and feta cheese. Served with garlic bread and your choice of dressing.
  price: $8.99
- name: Milano Chicken Salad
  ingredients:  Penne pasta, char-grilled chicken breast, blend of mixed greens and baby lettuce and roasted peppers covered with a fresh tomato balsamic vinaigrette and Parmesan cheese. Served with garlic bread.
  price: $9.85
- name: BBQ Chicken Salad
  ingredients:  Grilled marinated chicken breast in lime, Southwest dressing, romaine black beans, tomato, cheese and tortilla chips tossed with our BBQ ranch dressing. Served with garlic bread.
  price: $9.85
- name: Chopped Chicken Salad
  ingredients:  Grilled chicken breast, smoked bacon, iceberg and romaine lettuce, mozzarella cheese, red onions, tomato and basil with choice of dressing. Served with garlic bread.
  price: $9.85