SIDE ORDERS:
    - name: CALAMARI
      price: $6.50
    - name: CHICKEN TENDERS
      price: $4.95	
    - name: GARLIC BREAD
      price: $2.50 
    - name: MEATBALLS (2)
      price: $3.50
    - name: ITALIAN SAUSAGE (2)
      price: $3.50     
    - name: FRIED ZUCCHINI w/Ranch Dressing (7)
      price: $4.95
    - name: SOUP OF THE DAY
      price: $3.50
    - name: MOZZARELLA CHEESE STICKS w/Marinara Sauce (7)
      price: $4.95
    - name: FRENCH FRIES
      price: $3.95
    - name: GARLIC BREAD + CHEESE
      price: $3.25
    - name: SIDE OF MARINARA
      price: $1.85 
    - name: SIDE CREAM SAUCE
      price: $2.50
    - name: SIDE OF PINK SAUCE
      price: $1.85
    - name: SIDE OF PEPPERONCINI
      price: $1.00	
    - name: EXTRA DRESSING
      price: $0.50 each  